### ISSUE TITLE
Tips don't move when window is resized

### ISSUE THREAD

**Issue by kylefox** [jaz303/tipsy#13]

**Comment by jaz303** [comment]
Sorry don't have any interest in fixing this. Will accept patches though.

-J

**Comment by costa** [comment]
hmm, i wouldn't close it just because you are not planning to fix it anytime soon: it is only an issue with manual triggering (then, it's fairly reasonable to manually handle such annoyances) AND — what I came across in a project of mine — when it's inside a frame and the frame's size is changed, but the element stays in place, so no mouseout. So maybe someone will care enough to submit a patch...
