### ISSUE TITLE
Tooltip position not updated for elements that move

### ISSUE THREAD

**Issue by radum** [jaz303/tipsy#71]
It will be great if we can set an options or make it default for the tpoltip to move with the element. For example if I have a jQuery UI slider and I make a tipsy for the slider knob if I drag the slider the tip remain on the same position and after another hover it take the new coordinates.

It will be great if the mouse doesn't leave the knob and the dom element is dragged and moved the tooltop should move with it also.

**Comment by jaz303** [comment]
The problem is that tipsy appends its tooltips to document.body and as such they need to be positioned absolutely.

There are two simple ways to support what you require:
- Use `setInterval()` to constantly monitor the position of the target element and reposition the tooltip appropriately
- Provide a callback function that your code can use to tell the tooltip to reposition itself

IMO a solution using `setInterval` is hacky and it's a route I'd rather not go down.

Long term, the correct solution - which is one I've often flirted with implementing - would be to provide an option for tipsy to insert itself at a more relevant location in the DOM (e.g. as a child of the target element) and position itself relatively. Auto-repositioning behaviour would be gained "for free", as well as resolving another long-standing issue wherein tooltips persist even after their target elements are removed from the DOM.

-J

**Comment by radum** [comment]
That's true, I've hacked my version but it's really buggy and works only for my specific needs, but it will be great to hear some ideas from you on how we can change this for tipsy and perhaps we could fork a version of it.

**Comment by raduluchian** [comment]
I'm trying to have the same behaviour: jQueryUI Slider combined with Tipsy tooltip that shows the value of the slider. Can you share your solution for this perhaps?
